// SPDX-License-Identifier: Apache-2.0
//! The extension bridge: who is allowed to talk to CodeFactory.
//!
//! The extension backend inverts the usual direction. A browser extension
//! cannot be a server, so *it* connects out to a WebSocket that CodeFactory
//! listens on, and CodeFactory sends commands down that socket.
//!
//! That listener is the sensitive part. It sits on localhost with the ability
//! to read any page the user is signed in to, so anything that can connect to
//! it inherits that reach — including a web page running JavaScript in the same
//! browser, which can open a `ws://127.0.0.1` connection without asking anyone.
//! Two independent checks have to pass, and both are enforced here so a
//! transport bug cannot skip one:
//!
//!   1. **Origin must be a Chrome extension.** Browsers set `Origin` themselves
//!      and page JavaScript cannot forge it, so a page origin — or none at all
//!      — is refused outright. This is what keeps a random website from driving
//!      the bridge.
//!   2. **A pairing token must match.** Generated by the app, shown once in
//!      Settings, pasted into the extension. This is what keeps *another
//!      program* on the machine from connecting, which the Origin check alone
//!      cannot do.
//!
//! Neither check is sufficient alone: the Origin check stops pages but not
//! local processes, the token stops local processes but a page could read a
//! token that leaked into a page context.

use serde::{Deserialize, Serialize};

/// Where the pairing details live for the Settings UI to read.
pub const BRIDGE_FILE: &str = "bridge.json";

/// Published so the extension and the app agree on the handshake shape.
pub const PROTOCOL_VERSION: u32 = 1;

/// First frame the extension sends after connecting.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Hello {
    pub protocol_version: u32,
    pub token: String,
    /// Extension version, for diagnosing a stale install.
    #[serde(default)]
    pub extension_version: Option<String>,
}

/// What the app asks the extension to do.
///
/// Read-only for now. Acting on the browser the user actually uses is a much
/// larger step than reading it, and the permission rules already require a
/// prompt for every action, so it is deliberately not part of the first cut.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(tag = "cmd", rename_all = "snake_case")]
pub enum Command {
    /// Tabs the user has open, so the agent can work with what is already there.
    ListTabs,
    /// Readable content of a tab.
    Read { tab_id: i64 },
    /// Search within a tab.
    Find { tab_id: i64, query: String },
}

/// What comes back. Errors are values, not dropped frames, so a failed command
/// reports why instead of timing out.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Reply {
    pub id: u64,
    #[serde(default)]
    pub ok: bool,
    #[serde(default)]
    pub data: Option<serde_json::Value>,
    #[serde(default)]
    pub error: Option<String>,
}

/// Why a connection was refused.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Refusal {
    /// Not a browser extension — most likely a web page or a local program.
    NotAnExtension,
    /// Right shape, wrong or missing token.
    BadToken,
    /// Extension is older or newer than this app understands.
    ProtocolMismatch { theirs: u32 },
}

impl Refusal {
    /// Message safe to send back over the socket.
    ///
    /// Deliberately does not say *which* check failed in a way that helps a
    /// caller iterate — a probe learns "refused", not "the origin was fine, keep
    /// guessing the token".
    pub fn message(&self) -> String {
        match self {
            Self::ProtocolMismatch { theirs } => format!(
                "This CodeFactory speaks bridge protocol {PROTOCOL_VERSION}; the extension speaks {theirs}. Update whichever is older."
            ),
            _ => "Connection refused. Pair the CodeFactory extension from Settings.".into(),
        }
    }
}

/// Decide whether a connection may proceed.
pub fn authorize(origin: Option<&str>, hello: &Hello, expected_token: &str) -> Result<(), Refusal> {
    if !is_extension_origin(origin) {
        return Err(Refusal::NotAnExtension);
    }
    if hello.protocol_version != PROTOCOL_VERSION {
        return Err(Refusal::ProtocolMismatch {
            theirs: hello.protocol_version,
        });
    }
    if !token_matches(expected_token, &hello.token) {
        return Err(Refusal::BadToken);
    }
    Ok(())
}

/// True only for a Chrome extension origin.
///
/// The browser sets this header; page JavaScript cannot override it. An absent
/// Origin is refused too — a non-browser client simply omits it, and that is
/// exactly the case the token is not sufficient to cover on its own.
pub fn is_extension_origin(origin: Option<&str>) -> bool {
    let Some(origin) = origin else { return false };
    let Some(id) = origin.strip_prefix("chrome-extension://") else {
        return false;
    };
    // Extension ids are 32 lowercase letters a–p. Checking the shape keeps a
    // crafted origin like `chrome-extension://../..` from passing.
    id.len() == 32 && id.chars().all(|c| ('a'..='p').contains(&c))
}

/// Compare tokens without leaking length or position through timing.
pub fn token_matches(expected: &str, given: &str) -> bool {
    if expected.is_empty() {
        // No token configured means nothing is paired yet; refuse rather than
        // treating "unset" as "matches anything".
        return false;
    }
    let expected = expected.as_bytes();
    let given = given.as_bytes();
    let mut diff = expected.len() ^ given.len();
    for index in 0..expected.len().max(given.len()) {
        let a = expected.get(index).copied().unwrap_or(0);
        let b = given.get(index).copied().unwrap_or(0);
        diff |= usize::from(a ^ b);
    }
    diff == 0
}

/// A fresh pairing token.
///
/// A v4 UUID's 32 hex digits: short enough to paste, and random enough that
/// guessing is not a strategy against a listener that only exists while the app
/// is running. Reuses the uuid dependency rather than adding an RNG crate.
pub fn new_token() -> String {
    uuid::Uuid::new_v4().simple().to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn hello(token: &str) -> Hello {
        Hello {
            protocol_version: PROTOCOL_VERSION,
            token: token.into(),
            extension_version: None,
        }
    }

    const TOKEN: &str = "0123456789abcdef0123456789abcdef";
    const EXTENSION: &str = "chrome-extension://abcdefghijklmnopabcdefghijklmnop";

    #[test]
    fn a_paired_extension_is_allowed() {
        assert_eq!(authorize(Some(EXTENSION), &hello(TOKEN), TOKEN), Ok(()));
    }

    #[test]
    fn a_web_page_cannot_drive_the_bridge_even_with_the_token() {
        // The scenario this exists for: a site the user visits opens a
        // ws://127.0.0.1 connection. Browsers set Origin themselves, so the page
        // cannot pretend to be the extension.
        for origin in [
            "https://evil.example",
            "http://localhost:3000",
            "null",
            "file://",
        ] {
            assert_eq!(
                authorize(Some(origin), &hello(TOKEN), TOKEN),
                Err(Refusal::NotAnExtension),
                "{origin} must be refused"
            );
        }
    }

    #[test]
    fn a_local_program_with_no_origin_is_refused() {
        // A non-browser client omits Origin entirely. The token alone must not
        // be the only thing standing in the way.
        assert_eq!(
            authorize(None, &hello(TOKEN), TOKEN),
            Err(Refusal::NotAnExtension)
        );
    }

    #[test]
    fn a_crafted_extension_origin_does_not_pass_the_shape_check() {
        for origin in [
            "chrome-extension://../..",
            "chrome-extension://short",
            "chrome-extension://ABCDEFGHIJKLMNOPABCDEFGHIJKLMNOP",
            "chrome-extension://abcdefghijklmnopabcdefghijklmnoz", // 'z' is out of range
            "chrome-extension://",
        ] {
            assert!(!is_extension_origin(Some(origin)), "{origin} must fail");
        }
    }

    #[test]
    fn the_right_extension_with_the_wrong_token_is_refused() {
        assert_eq!(
            authorize(Some(EXTENSION), &hello("nope"), TOKEN),
            Err(Refusal::BadToken)
        );
    }

    #[test]
    fn an_unset_token_matches_nothing_rather_than_everything() {
        // "Not paired yet" must fail closed. Treating an empty expected token as
        // a wildcard would leave the bridge open on first run.
        assert!(!token_matches("", ""));
        assert!(!token_matches("", "anything"));
        assert_eq!(
            authorize(Some(EXTENSION), &hello(""), ""),
            Err(Refusal::BadToken)
        );
    }

    #[test]
    fn token_comparison_does_not_short_circuit_on_length_or_prefix() {
        assert!(token_matches(TOKEN, TOKEN));
        assert!(!token_matches(TOKEN, &TOKEN[..31]));
        assert!(!token_matches(TOKEN, &format!("{TOKEN}x")));
        // Shares a long prefix, differs at the end.
        let mut near = TOKEN.to_string();
        near.pop();
        near.push('0');
        assert!(!token_matches(TOKEN, &near));
    }

    #[test]
    fn a_version_mismatch_says_which_side_to_update() {
        let mut stale = hello(TOKEN);
        stale.protocol_version = PROTOCOL_VERSION + 1;
        let refusal = authorize(Some(EXTENSION), &stale, TOKEN).expect_err("refused");
        assert_eq!(
            refusal,
            Refusal::ProtocolMismatch {
                theirs: PROTOCOL_VERSION + 1
            }
        );
        assert!(refusal.message().contains("Update whichever is older"));
    }

    #[test]
    fn a_refusal_does_not_tell_a_prober_which_check_failed() {
        // Same text for both, so probing cannot separate "wrong origin" from
        // "wrong token" and iterate on the one that got closer.
        assert_eq!(
            Refusal::NotAnExtension.message(),
            Refusal::BadToken.message()
        );
    }

    #[test]
    fn tokens_are_pasteable_and_not_repeated() {
        let first = new_token();
        assert_eq!(first.len(), 32);
        assert!(first.chars().all(|c| c.is_ascii_hexdigit()));
        assert_ne!(first, new_token());
    }

    #[test]
    fn commands_round_trip_over_the_wire() {
        let json = serde_json::to_string(&Command::Find {
            tab_id: 7,
            query: "quarterly".into(),
        })
        .unwrap();
        assert!(json.contains("\"cmd\":\"find\""));

        let back: Command = serde_json::from_str(&json).unwrap();
        assert!(matches!(back, Command::Find { tab_id: 7, .. }));
    }
}
