#!/usr/bin/env bash
#
# install-dev-app-wrapper.sh — register the dev binary with macOS
# LaunchServices so it shows up to `computer-use.request_access` (and
# anywhere else that queries installed apps), enabling live UX
# verification of the running `target/debug/codefactory` from agent
# tooling.
#
# What this script does:
#   1. Build a minimal CodeFactoryDev.app bundle under /Applications/
#      whose CFBundleIdentifier is `com.codefactory.dev` (distinct from
#      the production `com.codefactory.app` so the two can coexist).
#   2. The bundle's executable is a thin shim that runs the project's
#      `pnpm tauri dev` with a dev-only Tauri identifier in this checkout.
#   3. Register the bundle with LaunchServices (`lsregister -f`).
#
# Idempotent. Re-running upgrades the existing wrapper.
#
# Why a wrapper instead of installing the release .app?
#   - release .app reads from production data dir; dev .app reads from
#     dev data dir, keeping the two cleanly separated.
#   - Running it always picks up the LATEST source — no rebuild needed
#     for frontend tweaks.
#   - The release pipeline still produces the real signed app for
#     end users; this is strictly for agent + developer live-verify.

set -euo pipefail
cd "$(dirname "$0")/.."

PROJECT_ROOT="$(pwd)"
# Optional overrides let concurrent tasks install isolated wrappers without
# replacing the shared CodeFactoryDev registration or data directory.
APP_PATH="${CODEFACTORY_DEV_APP_PATH:-/Applications/CodeFactoryDev.app}"
BUNDLE_ID="${CODEFACTORY_DEV_BUNDLE_ID:-com.codefactory.dev}"
DISPLAY_NAME="${CODEFACTORY_DEV_DISPLAY_NAME:-CodeFactoryDev}"
TAURI_CONFIG="${CODEFACTORY_DEV_TAURI_CONFIG:-src-tauri/tauri.dev.conf.json}"
DEV_HOME="${CODEFACTORY_DEV_HOME:-}"
LOG_PREFIX="${CODEFACTORY_DEV_LOG_PREFIX:-/tmp/CodeFactoryDev}"

echo "Installing $DISPLAY_NAME wrapper → $APP_PATH"
echo "  project root: $PROJECT_ROOT"

# ── Build the bundle skeleton ────────────────────────────────────────
rm -rf "$APP_PATH"
mkdir -p "$APP_PATH/Contents/MacOS"
mkdir -p "$APP_PATH/Contents/Resources"

# Info.plist — minimum keys to make LaunchServices treat this as a
# proper app and resolve "CodeFactoryDev" in request_access.
cat > "$APP_PATH/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>$DISPLAY_NAME</string>
    <key>CFBundleIdentifier</key>
    <string>$BUNDLE_ID</string>
    <key>CFBundleName</key>
    <string>$DISPLAY_NAME</string>
    <key>CFBundleDisplayName</key>
    <string>$DISPLAY_NAME</string>
    <key>CFBundleVersion</key>
    <string>0.0.0</string>
    <key>CFBundleShortVersionString</key>
    <string>0.0.0-dev</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>LSMinimumSystemVersion</key>
    <string>10.15</string>
    <key>NSHighResolutionCapable</key>
    <true/>
</dict>
</plist>
EOF

# Shim executable. The wrapper IS launched once at user "open"; the
# shim then exec's into pnpm tauri dev so the webview window appears
# with this bundle's identifier in the Dock and LaunchServices index.
#
# We resolve PNPM_PATH and PROJECT_ROOT at install time so the
# wrapper survives PATH and shell differences when launched from
# Finder, Spotlight, or open(1).
PNPM_PATH="$(which pnpm 2>/dev/null || true)"
if [ -z "$PNPM_PATH" ]; then
    echo "Error: pnpm not found on PATH. Install pnpm first." >&2
    exit 1
fi
HOST_CARGO_HOME="${CARGO_HOME:-$HOME/.cargo}"
HOST_RUSTUP_HOME="${RUSTUP_HOME:-$HOME/.rustup}"
CARGO_BIN="$HOST_CARGO_HOME/bin"

cat > "$APP_PATH/Contents/MacOS/$DISPLAY_NAME" <<EOF
#!/usr/bin/env bash
# CodeFactoryDev wrapper — launches dev tauri build of CodeFactory.
# Generated by scripts/install-dev-app-wrapper.sh — re-run to update.

export PATH="$CARGO_BIN:$(dirname "$PNPM_PATH"):/usr/local/bin:/opt/homebrew/bin:\$PATH"
export CARGO_HOME="$HOST_CARGO_HOME"
export RUSTUP_HOME="$HOST_RUSTUP_HOME"
if [ -n "$DEV_HOME" ]; then
  export HOME="$DEV_HOME"
fi
cd "$PROJECT_ROOT"

# Keep the interactive desktop session awake for the lifetime of the dev App.
# This prevents an unattended live-verification run from being interrupted by
# idle display/system sleep. A user-initiated lock is still respected.
# Log stdout/stderr so dev-app failures don't disappear silently.
exec /usr/bin/caffeinate -dimsu "$PNPM_PATH" tauri dev --config "$TAURI_CONFIG" >> "$LOG_PREFIX-\$(date +%Y%m%d).log" 2>&1
EOF

chmod +x "$APP_PATH/Contents/MacOS/$DISPLAY_NAME"

# ── Ad-hoc sign + clear quarantine ────────────────────────────────────
# Gatekeeper refuses to open unsigned bundles with -10669 even on the
# user's own machine. An ad-hoc signature (-s -) is enough to clear
# that gate for a local app the user clearly intends to run, and
# xattr removes the quarantine flag that gets set on freshly written
# bundles in some macOS configs.
codesign --force --deep --sign - "$APP_PATH" >/dev/null 2>&1 || true
xattr -dr com.apple.quarantine "$APP_PATH" 2>/dev/null || true

# ── Register with LaunchServices ─────────────────────────────────────
# -f forces a re-register (idempotent on repeat install).
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister \
    -f "$APP_PATH"

echo ""
echo "✅ Installed."
echo ""
echo "Verify (should print the bundle path):"
echo "  mdfind 'kMDItemCFBundleIdentifier == \"$BUNDLE_ID\"'"
echo ""
echo "Agents can now request access via either name:"
echo "  - \"$DISPLAY_NAME\""
echo "  - \"$BUNDLE_ID\""
echo ""
echo "Launch once manually (open from Finder, Spotlight, or:"
echo "  open -a $DISPLAY_NAME"
echo ""
echo "Logs land at $LOG_PREFIX-<YYYYMMDD>.log"
